import io
import json
from decimal import Decimal, ROUND_HALF_UP
import openpyxl
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
import pandas as pd
import streamlit as st
import plotly.express as px
import plotly.graph_objects as go
from sqlalchemy import text

# -----------------------------------------------------------------------------
# 1. Supabase 雲端資料庫連線與持久化操作
# -----------------------------------------------------------------------------
conn = st.connection("supabase", type="sql")

def init_db():
    """自動初始化 Supabase 資料表（如未建立）"""
    with conn.session as s:
        s.execute(text("""
            CREATE TABLE IF NOT EXISTS config (
                key TEXT PRIMARY KEY,
                value JSONB
            );
        """))
        s.execute(text("""
            CREATE TABLE IF NOT EXISTS daily_deltas (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                date_str TEXT NOT NULL,
                major TEXT NOT NULL,
                target_col TEXT NOT NULL,
                val NUMERIC(10, 2) NOT NULL
            );
        """))
        s.commit()

def load_data_from_supabase():
    """從 Supabase 實時讀取人員配置與增量流水 (ttl=0 禁用快取)"""
    try:
        df_raw = conn.query("SELECT value FROM config WHERE key = 'raw_persons';", ttl=0)
        raw_persons = df_raw.iloc[0]['value'] if not df_raw.empty else None

        df_animals = conn.query("SELECT value FROM config WHERE key = 'person_animals';", ttl=0)
        person_animals = df_animals.iloc[0]['value'] if not df_animals.empty else None

        df_deltas = conn.query("SELECT date_str, major, target_col, val FROM daily_deltas ORDER BY id ASC;", ttl=0)
        
        daily_deltas = {}
        if not df_deltas.empty:
            for _, row in df_deltas.iterrows():
                d = row['date_str']
                m = row['major']
                col = row['target_col']
                # 使用 Decimal 精确读取，避免 0.5 在浮点计算中出现异常
                v = float(Decimal(str(row['val'])).quantize(Decimal('0.1'), rounding=ROUND_HALF_UP))
                daily_deltas.setdefault(d, []).append((m, col, v))

        return raw_persons, person_animals, daily_deltas
    except Exception as e:
        st.error(f"資料庫讀取失敗: {e}")
        return None, None, {}

def save_config_to_supabase(raw_persons, person_animals):
    """保存人員及動物對照表配置至 Supabase"""
    with conn.session as s:
        s.execute(text("INSERT INTO config (key, value) VALUES ('raw_persons', :v) ON CONFLICT (key) DO UPDATE SET value = :v;"),
                  {"v": json.dumps(raw_persons, ensure_ascii=False)})
        s.execute(text("INSERT INTO config (key, value) VALUES ('person_animals', :v) ON CONFLICT (key) DO UPDATE SET value = :v;"),
                  {"v": json.dumps(person_animals, ensure_ascii=False)})
        s.commit()

def insert_delta_to_supabase(date_str, major, target_col, val):
    """实时新增一条流水记录；人数按 0.5 人为最小单位精确保存。"""
    exact_val = Decimal(str(val)).quantize(Decimal('0.1'), rounding=ROUND_HALF_UP)
    with conn.session as s:
        s.execute(
            text("INSERT INTO daily_deltas (date_str, major, target_col, val) VALUES (:d, :m, :c, :v);"),
            {"d": date_str, "m": major, "c": target_col, "v": exact_val}
        )
        s.commit()

def delete_delta_from_supabase(date_str, major, target_col, val):
    """實時刪除一條流水紀錄"""
    with conn.session as s:
        s.execute(text("""
            DELETE FROM daily_deltas 
            WHERE id IN (
                SELECT id FROM daily_deltas 
                WHERE date_str = :d AND major = :m AND target_col = :c AND val = :v 
                LIMIT 1
            );
        """), {"d": date_str, "m": major, "c": target_col, "v": float(val)})
        s.commit()

def reset_all_data_in_supabase():
    """清空並重置 Supabase 資料為初始數據"""
    raw_persons = ["覃小燕", "左丹丹", "梁书华", "古晨晓", "周欢喜"]
    person_animals = {"覃小燕": "🦊", "左丹丹": "🐼", "梁书华": "🦁", "古晨晓": "🐰", "周欢喜": "🐯"}
    daily_deltas = {
        "9月1日": [
            ("环保专业", "覃小燕_实际", 1.0), ("电气基础", "覃小燕_实际", 1.0),
            ("环保专业", "左丹丹_实际", 1.0), ("环保基础", "左丹丹_实际", 2.0),
            ("岩土基础", "梁书华_实际", 1.0), ("暖通基础", "周欢喜_实际", 1.0),
            ("233网校", "其他人员_实际", 1.0), ("电气基础", "其他人员_实际", 1.0)
        ],
        "9月2日": [
            ("电气基础", "覃小燕_实际", 2.0), ("环评专业", "左丹丹_实际", 1.0),
            ("暖通专业", "梁书华_实际", 1.0), ("发输电专业", "其他人员_实际", 1.0),
            ("暖通基础", "其他人员_实际", 1.0), ("水利水电基础", "其他人员_实际", 1.0)
        ],
        "9月3日": [
            ("环保基础", "覃小燕_实际", 1.0)
        ]
    }
    
    with conn.session as s:
        s.execute(text("TRUNCATE TABLE config;"))
        s.execute(text("TRUNCATE TABLE daily_deltas;"))
        s.execute(text("INSERT INTO config (key, value) VALUES ('raw_persons', :v);"), {"v": json.dumps(raw_persons, ensure_ascii=False)})
        s.execute(text("INSERT INTO config (key, value) VALUES ('person_animals', :v);"), {"v": json.dumps(person_animals, ensure_ascii=False)})
        
        for d, items in daily_deltas.items():
            for m, col, v in items:
                s.execute(text("INSERT INTO daily_deltas (date_str, major, target_col, val) VALUES (:d, :m, :c, :v);"),
                          {"d": d, "m": m, "c": col, "v": float(v)})
        s.commit()
    return raw_persons, person_animals, daily_deltas

init_db()

# -----------------------------------------------------------------------------
# 2. 頁面基本配置與全域響應式 CSS 注入
# -----------------------------------------------------------------------------
st.set_page_config(page_title="招生數據動態管理與多維分析系統", page_icon="📊", layout="wide", initial_sidebar_state="expanded")

st.markdown("""
<style>
    @media (max-width: 768px) {
        .kpi-card { height: auto !important; padding: 10px !important; margin-bottom: 8px; }
        .kpi-value { font-size: 20px !important; }
        .kpi-title { font-size: 12px !important; }
    }
    .kpi-card {
        background-color: #F8F9FA; border: 1px solid #E9ECEF; border-radius: 10px;
        padding: 16px; box-shadow: 0 2px 4px rgba(0,0,0,0.03); height: 105px;
        display: flex; flex-direction: column; justify-content: space-between; box-sizing: border-box;
    }
    .kpi-title { font-size: 14px; color: #31333F; font-weight: 500; display: flex; align-items: center; gap: 6px; }
    .kpi-body { display: flex; align-items: baseline; gap: 10px; }
    .kpi-value { font-size: 28px; font-weight: 700; color: #0E1117; font-family: "Source Sans Pro", sans-serif; line-height: 1; }
    .kpi-delta { font-size: 13px; font-weight: 600; color: #FF2B2B; background-color: #FFE6E6; padding: 2px 8px; border-radius: 12px; display: inline-flex; align-items: center; white-space: nowrap; }
    .table-container { width: 100%; overflow-x: auto; -webkit-overflow-scrolling: touch; border-radius: 8px; border: 1px solid #7F7F7F; }
    div[data-testid="stForm"] { border-radius: 10px; background-color: #FAFAFA; }
</style>
""", unsafe_allow_html=True)

st.title("📊 招生数据动态管理与多维分析系统")
st.caption("2026年9月数据 - Supabase 云端实时同步版 | 数据永久保存")
st.markdown("---")

# -----------------------------------------------------------------------------
# 3. 基礎數據定義與 Supabase 數據載入
# -----------------------------------------------------------------------------
DEFAULT_MAJORS = [
    ("给排水专业", 19, [4, 3, 6, 3, 3]), ("发输电专业", 10, [2, 3, 2, 1, 2]),
    ("供配电专业", 11, [3, 4, 2, 1, 1]), ("环保专业", 13, [4, 2, 2, 3, 2]),
    ("环评专业", 9, [2, 2, 1, 3, 1]), ("岩土专业", 8, [2, 2, 2, 1, 1]),
    ("暖通专业", 16, [3, 3, 3, 2, 5]), ("结构专业", 20, [4, 4, 4, 5, 3]),
    ("道路专业", 5, [1, 1, 1, 1, 1]), ("233网校", 5, [1, 1, 1, 1, 1]),
    ("电气基础", 53, [11, 16, 11, 8, 7]), ("环保基础", 30, [9, 6, 6, 5, 4]),
    ("岩土基础", 36, [9, 8, 7, 6, 6]), ("水基础", 17, [4, 4, 5, 2, 2]),
    ("暖通基础", 27, [5, 5, 4, 4, 9]), ("结构基础", 9, [2, 2, 1, 2, 1]),
    ("公共基础", 4, [2, 1, 1, 0, 1]), ("道路基础", 6, [1, 1, 1, 1, 2]),
    ("水利水电基础", 10, [2, 2, 3, 2, 1]),
]

DATES = [f"9月{i}日" for i in range(1, 31)]
ALL_ANIMALS = ["🦊", "🐼", "🦁", "🐰", "🐯", "🐱", "🐶", "🐻", "🐨", "🐮", "🐵", "🐥", "🐸", "🐷", "🐹", "🦄"]

def build_base_targets_df(persons):
    base_data = []
    for idx, (name, total_target, person_tgts) in enumerate(DEFAULT_MAJORS, 1):
        row = {"序号": idx, "专业/基础名称": name, "目标人数": float(total_target)}
        for p_idx, p in enumerate(persons):
            row[f"{p}_目标"] = float(person_tgts[p_idx]) if p_idx < len(person_tgts) else 0.0
            row[f"{p}_实际"] = 0.0
        row["其他人员_目标"] = 0.0
        row["其他人员_实际"] = 0.0
        base_data.append(row)
    return pd.DataFrame(base_data)

db_raw_persons, db_person_animals, db_daily_deltas = load_data_from_supabase()

if db_raw_persons is None:
    db_raw_persons, db_person_animals, db_daily_deltas = reset_all_data_in_supabase()

st.session_state["raw_persons"] = db_raw_persons
st.session_state["person_animals"] = db_person_animals
st.session_state["daily_deltas"] = db_daily_deltas
st.session_state["base_targets"] = build_base_targets_df(st.session_state["raw_persons"])
RAW_PERSONS = st.session_state["raw_persons"]

# -----------------------------------------------------------------------------
# 4. 側邊欄：脫敏管理 & 映射關係
# -----------------------------------------------------------------------------
st.sidebar.title("🛠️ 数据管理与设置")
enable_anonymize = st.sidebar.checkbox("开启数据脱敏 / 纯动物符号模式", value=True)

alias_map = {p: (st.session_state["person_animals"].get(p, "🐱") if enable_anonymize else p) for p in RAW_PERSONS}
inv_alias_map = {v: k for k, v in alias_map.items()}

PERSONS = [alias_map[p] for p in RAW_PERSONS]

if enable_anonymize:
    with st.sidebar.expander("👁️ 视角对照表（管理者隐私预览）", expanded=False):
        st.dataframe(pd.DataFrame({"真实姓名": RAW_PERSONS, "代称动物": PERSONS}), hide_index=True, use_container_width=True)

used_animals = set(st.session_state["person_animals"].values())
available_animals = [a for a in ALL_ANIMALS if a not in used_animals]

with st.sidebar.expander("👥 人员增删管理"):
    new_p_name = st.text_input("姓名", placeholder="例如：张三", key="new_person_name_input")
    if available_animals:
        new_p_emoji = st.selectbox("分配未被使用的动物标志", available_animals, key="new_person_emoji_input")
    else:
        st.warning("所有预设动物标志已被分配完毕！")
        new_p_emoji = None

    if st.button("➕ 确认新增", use_container_width=True):
        if new_p_name and new_p_emoji and new_p_name not in RAW_PERSONS:
            st.session_state["raw_persons"].append(new_p_name)
            st.session_state["person_animals"][new_p_name] = new_p_emoji
            save_config_to_supabase(st.session_state["raw_persons"], st.session_state["person_animals"])
            st.sidebar.success(f"已新增：{new_p_name} ({new_p_emoji})")
            st.rerun()

# -----------------------------------------------------------------------------
# 5. 快捷錄入與刪減招生數據 (支援 0.5 強制浮點數)
# -----------------------------------------------------------------------------
st.sidebar.markdown("---")
st.sidebar.subheader("✏️ 招生人数 增加 / 删减")
op_mode = st.sidebar.radio("操作模式：", ["➕ 新增完成人数", "➖ 删减完成人数"], horizontal=True)

with st.sidebar.form("add_delta_form", clear_on_submit=True):
    input_date = st.selectbox("日期", DATES, index=2)
    input_major = st.selectbox("专业/基础", list(st.session_state["base_targets"]["专业/基础名称"]))
    input_person_disp = st.selectbox("归属人员", PERSONS + ["其他人员"])
    
    # 人数输入严格以 0.5 人为单位；数据库也以 NUMERIC 精确保存
    input_val = st.number_input(
        "变动人数（支持 0.5 人）",
        min_value=0.5,
        max_value=100.0,
        value=0.5,
        step=0.5,
        format="%.1f"
    )

    if st.form_submit_button("确认提交修改", use_container_width=True):
        raw_person_name = inv_alias_map.get(input_person_disp, input_person_disp)
        target_col = f"{raw_person_name}_实际" if raw_person_name != "其他人员" else "其他人员_实际"

        exact_input = Decimal(str(input_val)).quantize(Decimal("0.1"), rounding=ROUND_HALF_UP)
        if (exact_input * 2) != (exact_input * 2).to_integral_value():
            st.sidebar.error("人数必须以 0.5 人为最小单位。")
        else:
            actual_change = exact_input if "新增" in op_mode else -exact_input
            insert_delta_to_supabase(input_date, input_major, target_col, actual_change)
            st.sidebar.success(
                f"已成功同步至云端：{input_date} {input_major} - {input_person_disp} "
                f"({actual_change:+.1f}人)"
            )
            st.rerun()

with st.sidebar.expander("🗑️ 招生流水明细与单条删除"):
    del_date = st.selectbox("选择要查验的日期：", DATES, index=2, key="del_date_sel")
    day_records = st.session_state["daily_deltas"].get(del_date, [])
    if not day_records:
        st.info("该日期暂无记录")
    else:
        for r_idx, item in enumerate(day_records):
            m_name, p_col, val_num = item if len(item) == 3 else ("电气基础", item[0], float(item[1]))
            val_num = float(val_num)
            p_raw = p_col.replace("_实际", "")
            c_lbl, c_btn = st.columns([3, 1])
            disp_name = alias_map.get(p_raw, p_raw)
            c_lbl.caption(f"{m_name} | {disp_name} | {'+' if val_num>0 else ''}{val_num:.1f}".rstrip('0').rstrip('.') + "人")
            if c_btn.button("删除", key=f"del_{del_date}_{r_idx}"):
                delete_delta_from_supabase(del_date, m_name, p_col, val_num)
                st.sidebar.success("已从云端删除该条纪录")
                st.rerun()

st.sidebar.markdown("---")
if st.sidebar.button("💥 重置（初始化全量数据）", use_container_width=True):
    reset_all_data_in_supabase()
    st.sidebar.info("已重置 Supabase 云端数据库！")
    st.rerun()

# -----------------------------------------------------------------------------
# 6. 時間彙總粒度篩選與數據計算
# -----------------------------------------------------------------------------
st.subheader("🗓️ 时间汇总粒度筛选")
f_col1, f_col2 = st.columns(2)

with f_col1:
    time_granularity_type = st.selectbox("选择时间汇总粒度：", ["按月（全月 / 累计至指定日期）", "按周（周度汇总）", "按日（单日切片）"])

with f_col2:
    if time_granularity_type == "按日（单日切片）":
        selected_time_range = st.selectbox("选择具体日期：", DATES, index=2)
        selected_dates_list = [selected_time_range]
    elif time_granularity_type == "按周（周度汇总）":
        selected_time_range = st.selectbox("选择具体周：", ["2026年第36周 (9月1日-9月7日)"])
        selected_dates_list = DATES[:7]
    else:
        month_scope = st.radio("月度统计范围：", ["9月全月（9月1日-9月30日）", "累计至指定日期（如 9月1日-9月10日）"], horizontal=True)
        if "全月" in month_scope:
            selected_time_range = "2026年9月全月"
            selected_dates_list = DATES
        else:
            end_date = st.selectbox("选择截止日期（包含当日）：", DATES, index=9)
            end_idx = DATES.index(end_date) + 1
            selected_dates_list = DATES[:end_idx]
            selected_time_range = f"9月1日 至 {end_date} 累计"

def get_processed_df_by_dates(dates_list):
    df_result = build_base_targets_df(st.session_state["raw_persons"])
    act_cols = [c for c in df_result.columns if c.endswith("_实际")]
    for col in act_cols: 
        df_result[col] = 0.0

    for d in dates_list:
        for item in st.session_state["daily_deltas"].get(d, []):
            major, col, val = item if len(item) == 3 else ("电气基础", item[0], float(item[1]))
            if col in df_result.columns:
                mask = df_result["专业/基础名称"] == major
                current = Decimal(str(df_result.loc[mask, col].iloc[0])) if mask.any() else Decimal("0")
                exact_val = Decimal(str(val)).quantize(Decimal("0.1"), rounding=ROUND_HALF_UP)
                new_val = (current + exact_val).quantize(Decimal("0.1"), rounding=ROUND_HALF_UP)
                df_result.loc[mask, col] = float(new_val)
    return df_result

calc_df = get_processed_df_by_dates(selected_dates_list)
act_cols = [c for c in calc_df.columns if c.endswith("_实际")]
calc_df["实际完成"] = calc_df[act_cols].sum(axis=1).round(1)
calc_df["与目标之差"] = (
    calc_df["实际完成"] - calc_df["目标人数"]
).round(1)

num_cols = [c for c in calc_df.columns if c not in ["序号", "专业/基础名称"]]
sum_row = {"专业/基础名称": "合计"}
for c in num_cols:
    if c in calc_df.columns and pd.api.types.is_numeric_dtype(calc_df[c]):
        sum_row[c] = round(float(calc_df[c].sum()), 1)
    else:
        sum_row[c] = float(calc_df[c].sum())

diff_row = {"专业/基础名称": "与目标之差"}
for p in RAW_PERSONS:
    diff_row[f"{p}_目标"] = ""
    diff_row[f"{p}_实际"] = sum_row[f"{p}_实际"] - sum_row[f"{p}_目标"]
diff_row["其他人员_目标"] = ""
diff_row["其他人员_实际"] = sum_row.get("其他人员_实际", 0.0)
diff_row.update({"目标人数": "", "实际完成": "", "与目标之差": sum_row["与目标之差"]})

total_target_cum = sum_row["目标人数"]
total_actual_cum = sum_row["实际完成"]
cum_rate_val = round(
    (float(total_actual_cum) / float(total_target_cum) * 100)
    if total_target_cum > 0 else 0,
    2
)
rate_row = {"专业/基础名称": "目标人数完成比例", "实际完成": f"{cum_rate_val:.2f}%"}

avg_per_day = round(
    float(total_actual_cum) / len(selected_dates_list),
    1
) if len(selected_dates_list) > 0 else 0.0

def fmt_num(v):
    """统一数字显示，确保 0.5 等小数不会在表格中被显示为整数。"""
    if v == "" or v is None:
        return ""
    try:
        val = float(v)

        # 消除浮点计算产生的极小误差，例如 0.49999999999999994
        val = round(val, 1)

        # 避免显示 -0.0
        if abs(val) < 0.000001:
            val = 0.0

        # 整数仍显示整数，小数保留1位
        if val.is_integer():
            return str(int(val))
        return f"{val:.1f}"
    except (ValueError, TypeError):
        return str(v)

m_col1, m_col2, m_col3, m_col4 = st.columns(4)
m_col1.markdown(f'<div class="kpi-card"><div class="kpi-title">🎯 总目标人数</div><div class="kpi-body"><div class="kpi-value">{fmt_num(total_target_cum)} 人</div></div></div>', unsafe_allow_html=True)
m_col2.markdown(f'<div class="kpi-card"><div class="kpi-title">✅ 实际完成人数</div><div class="kpi-body"><div class="kpi-value">{fmt_num(total_actual_cum)} 人</div><div class="kpi-delta">↓ {fmt_num(sum_row["与目标之差"])} 人</div></div></div>', unsafe_allow_html=True)
m_col3.markdown(f'<div class="kpi-card"><div class="kpi-title">📈 目标完成比例</div><div class="kpi-body"><div class="kpi-value">{cum_rate_val:.2f}%</div></div></div>', unsafe_allow_html=True)
m_col4.markdown(f'<div class="kpi-card"><div class="kpi-title">📅 选定区间日均新增</div><div class="kpi-body"><div class="kpi-value">{avg_per_day:.1f} 人/天</div></div></div>', unsafe_allow_html=True)

# -----------------------------------------------------------------------------
# 7. HTML 表格渲染
# -----------------------------------------------------------------------------
def build_html_document(df, sum_r, diff_r, rate_r, p_names, raw_p_names, range_title):
    rows_html = ""
    for idx, row in df.iterrows():
        person_cells = "".join([f'<td class="num">{fmt_num(row[f"{rp}_目标"])}</td><td class="num">{fmt_num(row[f"{rp}_实际"])}</td>' for rp in raw_p_names])
        rows_html += f'<tr><td class="num">{int(row["序号"])}</td><td class="zh">{row["专业/基础名称"]}</td><td class="num">{fmt_num(row["目标人数"])}</td>{person_cells}<td class="num">{fmt_num(row["其他人员_目标"])}</td><td class="num">{fmt_num(row["其他人员_实际"])}</td><td class="num">{fmt_num(row["目标人数"])}</td><td class="num">{fmt_num(row["实际完成"])}</td><td class="num">{fmt_num(row["与目标之差"])}</td></tr>'

    person_headers = "".join([f'<th colspan="2" class="bg-person">{p}</th>' for p in p_names])
    sub_headers = '<th class="bg-header">目标</th><th class="bg-header">实际</th>' * (len(p_names) + 1)
    
    sum_person_cells = "".join([f'<td class="bg-total num">{fmt_num(sum_r[f"{rp}_目标"])}</td><td class="bg-total num">{fmt_num(sum_r[f"{rp}_实际"])}</td>' for rp in raw_p_names])
    diff_person_cells = "".join([f'<td class="bg-total" colspan="2"><b class="num">{fmt_num(diff_r[f"{rp}_实际"])}</b></td>' for rp in raw_p_names])
    
    total_colspan = 7 + (len(p_names) + 1) * 2

    return f"""
    <!DOCTYPE html><html><head><meta charset="utf-8">
    <style>
        body {{ margin: 0; padding: 0; font-family: SimSun, "Times New Roman", serif; background-color: #ffffff; }}
        .table-container {{ width: 100%; max-height: 640px; overflow: auto; -webkit-overflow-scrolling: touch; border-radius: 8px; border: 1px solid #7F7F7F; }}
        table {{ width: 100%; border-collapse: collapse; font-size: 13px; text-align: center; }}
        th, td {{ border: 1px solid #7F7F7F; padding: 6px 4px; font-weight: normal; color: #000000; }}
        .bg-title {{ background-color: #D9EAD3; font-size: 16px; font-weight: bold; padding: 8px 0; }}
        .bg-header {{ background-color: #F2F2F2; font-weight: bold; }}
        .bg-person {{ background-color: #D0E0E3; font-weight: bold; font-size: 16px; }}
        .bg-total {{ background-color: #D9EAD3; font-weight: bold; }}
        .num {{ font-family: "Times New Roman", serif; }}
        .zh {{ font-family: SimSun, serif; }}
    </style></head><body><div class="table-container"><table>
        <tr><td colspan="{total_colspan}" class="bg-title">2026年9月招生数据动态表({range_title})</td></tr>
        <tr><th rowspan="2" class="bg-header">序号</th><th rowspan="2" class="bg-header">专业/基础名称</th><th rowspan="2" class="bg-header">目标人数</th>{person_headers}<th colspan="2" class="bg-person">其他人员</th><th rowspan="2" class="bg-header">目标人数</th><th rowspan="2" class="bg-header">实际完成</th><th rowspan="2" class="bg-header">与目标之差</th></tr>
        <tr>{sub_headers}</tr>
        {rows_html}
        <tr><td class="bg-total"></td><td class="bg-total zh"><b>{sum_r['专业/基础名称']}</b></td><td class="bg-total num"><b>{fmt_num(sum_r['目标人数'])}</b></td>{sum_person_cells}<td class="bg-total num"><b>0</b></td><td class="bg-total num"><b>{fmt_num(sum_r['其他人员_实际'])}</b></td><td class="bg-total num"><b>{fmt_num(sum_r['目标人数'])}</b></td><td class="bg-total num"><b>{fmt_num(sum_r['实际完成'])}</b></td><td class="bg-total num"><b>{fmt_num(sum_r['与目标之差'])}</b></td></tr>
        <tr><td class="bg-total"></td><td class="bg-total zh"><b>{diff_r['专业/基础名称']}</b></td><td class="bg-total"></td>{diff_person_cells}<td class="bg-total" colspan="2"><b class="num">{fmt_num(diff_r['其他人员_实际'])}</b></td><td class="bg-total"></td><td class="bg-total"></td><td class="bg-total num"><b>{fmt_num(diff_r['与目标之差'])}</b></td></tr>
        <tr><td class="bg-total zh" colspan="{total_colspan}" style="text-align: center; font-size: 14px; padding: 8px 0;"><b>{rate_r['专业/基础名称']}：<span class="num">{rate_r['实际完成']}</span></b></td></tr>
    </table></div></body></html>
    """

st.markdown(f"### 📝 2026年9月招生数据动态表({selected_time_range})")
st.components.v1.html(build_html_document(calc_df, sum_row, diff_row, rate_row, PERSONS, RAW_PERSONS, selected_time_range), height=680, scrolling=True)

# -----------------------------------------------------------------------------
# 8. 視覺化圖表展示
# -----------------------------------------------------------------------------
st.markdown("---")
st.markdown("### 📊 多维数据分析图表")

c1, c2 = st.columns(2)

with c1:
    fig_person = go.Figure(data=[
        go.Bar(name="目标人数", x=PERSONS, y=[sum_row[f"{p}_目标"] for p in RAW_PERSONS], marker_color="#0B3C5D", text=[fmt_num(sum_row[f"{p}_目标"]) for p in RAW_PERSONS], textposition="outside"),
        go.Bar(name="实际完成", x=PERSONS, y=[sum_row[f"{p}_实际"] for p in RAW_PERSONS], marker_color="#FF3D00", text=[fmt_num(sum_row[f"{p}_实际"]) for p in RAW_PERSONS], textposition="outside")
    ])
    fig_person.update_layout(title="<b>各成员目标 vs 实际完成对比</b>", barmode="group", plot_bgcolor="#FFFFFF", margin=dict(l=20, r=20, t=50, b=20), yaxis=dict(gridcolor="#E0E0E0"))
    st.plotly_chart(fig_person, use_container_width=True)

with c2:
    active_majors = calc_df[calc_df["实际完成"] > 0].sort_values(by="实际完成", ascending=False)
    if not active_majors.empty:
        fig_major = px.bar(active_majors, x="实际完成", y="专业/基础名称", orientation="h", title="<b>当前切片有成交的专业排行</b>", text="实际完成", color="专业/基础名称", color_discrete_sequence=px.colors.qualitative.Bold)
        fig_major.update_traces(textposition="outside")
    else:
        fig_major = px.bar(x=[0], y=["无成交记录"], orientation="h", title="<b>当前切片无成交记录</b>")
    fig_major.update_layout(yaxis={"categoryorder": "total ascending"}, showlegend=False, plot_bgcolor="#FFFFFF", margin=dict(l=20, r=20, t=50, b=20), xaxis=dict(gridcolor="#E0E0E0"))
    st.plotly_chart(fig_major, use_container_width=True)

c3, c4 = st.columns(2)

with c3:
    daily_counts = []
    for d in selected_dates_list:
        records = st.session_state["daily_deltas"].get(d, [])
        day_sum = sum([float(item[2] if len(item) == 3 else item[1]) for item in records])
        daily_counts.append({"日期": d, "每日新增": day_sum})
    
    df_trend = pd.DataFrame(daily_counts)
    fig_trend = px.line(df_trend, x="日期", y="每日新增", markers=True, title="<b>每日新增招生趋势 (折线图)</b>", text="每日新增")
    fig_trend.update_traces(textposition="top center", line_color="#2E7D32", line_width=3, marker_size=8)
    fig_trend.update_layout(plot_bgcolor="#FFFFFF", margin=dict(l=20, r=20, t=50, b=20), yaxis=dict(gridcolor="#E0E0E0"))
    st.plotly_chart(fig_trend, use_container_width=True)

with c4:
    pie_labels = PERSONS + ["其他人员"]
    pie_values = [sum_row[f"{p}_实际"] for p in RAW_PERSONS] + [sum_row["其他人员_实际"]]
    
    if sum(pie_values) > 0:
        fig_pie = px.pie(names=pie_labels, values=pie_values, title="<b>人员招生贡献占比 (饼状图)</b>", hole=0.3, color_discrete_sequence=px.colors.qualitative.Pastel)
        fig_pie.update_traces(textinfo="label+percent+value")
    else:
        fig_pie = px.pie(names=["暂无数据"], values=[1], title="<b>人员招生贡献占比 (暂无数据)</b>", hole=0.3)
    fig_pie.update_layout(margin=dict(l=20, r=20, t=50, b=20))
    st.plotly_chart(fig_pie, use_container_width=True)

# -----------------------------------------------------------------------------
# 9. Excel 完整帶樣式導出
# -----------------------------------------------------------------------------
def export_color_excel(calc_df, sum_row, diff_row, rate_row, persons_disp, raw_persons):
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "招生数据动态表"
    ws.views.sheetView[0].showGridLines = True

    BORDER_THIN = Border(left=Side(style="thin", color="7F7F7F"), right=Side(style="thin", color="7F7F7F"), top=Side(style="thin", color="7F7F7F"), bottom=Side(style="thin", color="7F7F7F"))
    ALIGN_CENTER = Alignment(horizontal="center", vertical="center")

    total_cols = 7 + (len(raw_persons) + 1) * 2
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=total_cols)
    ws["A1"] = f"2026年9月招生数据动态表({selected_time_range})"
    ws["A1"].font = Font(name="SimSun", size=14, bold=True)
    ws["A1"].fill = PatternFill(start_color="D9EAD3", fill_type="solid")
    ws["A1"].alignment = ALIGN_CENTER

    ws.merge_cells("A2:A3"); ws["A2"] = "序号"
    ws.merge_cells("B2:B3"); ws["B2"] = "专业/基础名称"
    ws.merge_cells("C2:C3"); ws["C2"] = "目标人数"

    col_idx = 4
    for p in persons_disp + ["其他人员"]:
        ws.merge_cells(start_row=2, start_column=col_idx, end_row=2, end_column=col_idx + 1)
        ws.cell(row=2, column=col_idx, value=p).fill = PatternFill(start_color="D0E0E3", fill_type="solid")
        ws.cell(row=3, column=col_idx, value="目标人数")
        ws.cell(row=3, column=col_idx + 1, value="实际完成")
        col_idx += 2

    other_col = col_idx
    for name, offset in [("目标人数", 0), ("实际完成", 1), ("与目标之差", 2)]:
        ws.merge_cells(start_row=2, start_column=other_col+offset, end_row=3, end_column=other_col+offset)
        ws.cell(row=2, column=other_col+offset, value=name)

    for r in range(2, 4):
        for c in range(1, total_cols + 1):
            cell = ws.cell(row=r, column=c)
            if not cell.fill.start_color.rgb: cell.fill = PatternFill(start_color="EFEFEF", fill_type="solid")
            cell.font = Font(name="SimSun", size=10, bold=True)
            cell.alignment = ALIGN_CENTER
            cell.border = BORDER_THIN

    curr_r = 4
    for idx, row in calc_df.iterrows():
        ws.cell(row=curr_r, column=1, value=int(row["序号"]))
        ws.cell(row=curr_r, column=2, value=row["专业/基础名称"])
        ws.cell(row=curr_r, column=3, value=row["目标人数"])

        c_offset = 4
        for rp in raw_persons:
            ws.cell(row=curr_r, column=c_offset, value=row[f"{rp}_目标"])
            ws.cell(row=curr_r, column=c_offset + 1, value=round(float(row[f"{rp}_实际"]), 1) if row[f"{rp}_实际"] != "" else "")
            c_offset += 2

        ws.cell(row=curr_r, column=c_offset, value=row.get("其他人员_目标", 0) or "")
        ws.cell(row=curr_r, column=c_offset + 1, value=round(float(row.get("其他人员_实际", 0)), 1) if row.get("其他人员_实际", 0) != "" else "")
        ws.cell(row=curr_r, column=c_offset + 2, value=row["目标人数"])
        ws.cell(row=curr_r, column=c_offset + 3, value=row["实际完成"])
        ws.cell(row=curr_r, column=c_offset + 4, value=row["与目标之差"])

        for c in range(1, total_cols + 1):
            cell = ws.cell(row=curr_r, column=c)
            cell.alignment = ALIGN_CENTER
            cell.border = BORDER_THIN
            # 数字列统一保留1位小数，0.5 在 Excel 中不会显示成 1
            if c >= 3:
                cell.number_format = '0.0'
        curr_r += 1

    for r_data in [sum_row, diff_row]:
        ws.cell(row=curr_r, column=2, value=r_data["专业/基础名称"])
        ws.cell(row=curr_r, column=3, value=r_data.get("目标人数", ""))

        c_offset = 4
        for rp in raw_persons:
            if r_data["专业/基础名称"] == "与目标之差":
                ws.merge_cells(start_row=curr_r, start_column=c_offset, end_row=curr_r, end_column=c_offset+1)
                ws.cell(row=curr_r, column=c_offset, value=r_data.get(f"{rp}_实际", ""))
            else:
                ws.cell(row=curr_r, column=c_offset, value=r_data.get(f"{rp}_目标", ""))
                ws.cell(row=curr_r, column=c_offset + 1, value=r_data.get(f"{rp}_实际", ""))
            c_offset += 2

        if r_data["专业/基础名称"] == "与目标之差":
            ws.merge_cells(start_row=curr_r, start_column=c_offset, end_row=curr_r, end_column=c_offset+1)
            ws.cell(row=curr_r, column=c_offset, value=r_data.get("其他人员_实际", ""))
        else:
            ws.cell(row=curr_r, column=c_offset, value=0)
            ws.cell(row=curr_r, column=c_offset + 1, value=r_data.get("其他人员_实际", ""))

        ws.cell(row=curr_r, column=c_offset + 2, value=r_data.get("目标人数", ""))
        ws.cell(row=curr_r, column=c_offset + 3, value=r_data.get("实际完成", ""))
        ws.cell(row=curr_r, column=c_offset + 4, value=r_data.get("与目标之差", ""))

        for c in range(1, total_cols + 1):
            cell = ws.cell(row=curr_r, column=c)
            cell.alignment = ALIGN_CENTER
            cell.border = BORDER_THIN
            cell.fill = PatternFill(start_color="D9EAD3", fill_type="solid")
            if c >= 3:
                cell.number_format = '0.0'
        curr_r += 1

    ws.merge_cells(start_row=curr_r, start_column=1, end_row=curr_r, end_column=total_cols)
    ws.cell(row=curr_r, column=1, value=f"{rate_row['专业/基础名称']}：{rate_row['实际完成']}")
    for c in range(1, total_cols + 1):
        cell = ws.cell(row=curr_r, column=c)
        cell.alignment = ALIGN_CENTER; cell.border = BORDER_THIN; cell.fill = PatternFill(start_color="D9EAD3", fill_type="solid")
        cell.font = Font(name="SimSun", size=11, bold=True)

    output = io.BytesIO()
    wb.save(output)
    return output.getvalue()

st.markdown("---")
st.markdown("### 📥 数据导出")
st.download_button(
    label="📥 导出带样式的 Excel 报表",
    data=export_color_excel(calc_df, sum_row, diff_row, rate_row, PERSONS, RAW_PERSONS),
    file_name=f"2026年9月招生数据动态表_{selected_time_range}.xlsx",
    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    use_container_width=True
)
